[colors.primary]
background = "#282828"
foreground = "#d4be98"

[colors.normal]
black = "#867970"
blue = "#82a9a0"
cyan = "#8daf87"
green = "#a3ae6d"
magenta = "#cb8e9e"
red = "#d67b76"
white = "#d7c5a7"
yellow = "#cba364"

[colors.bright]
black = "#867970"
blue = "#82a9a0"
cyan = "#8daf87"
green = "#a3ae6d"
magenta = "#cb8e9e"
red = "#d67b76"
white = "#d7c5a7"
yellow = "#cba364"
