[colors.primary]
background = '#272822'
foreground = '#F0F9FF'

[colors.normal]
black = '#858480'
red = '#A6674C'
green = '#B0B9A8'
yellow = '#DCB482'
blue = '#5B7C99'
magenta = '#7B7693'
cyan = '#8AABAC'
white = '#E6E4E0'

[colors.bright]
black = '#858480'
red = '#A6674C'
green = '#B0B9A8'
yellow = '#DCB482'
blue = '#5B7C99'
magenta = '#7B7693'
cyan = '#9EC3C4'
white = '#E6E4E0'
