return function(colours)
  return {
    TSAnnotation = { fg = colours.colour4 },
    TSAttribute = { fg = colours.colour4 },
    TSBoolean = { fg = colours.colour4 },
    TSCharacter = { fg = colours.colour3 },
    TSComment = { fg = colours.fg_faded, italic = true },
    TSConditional = { fg = colours.colour0 },
    TSConstant = { fg = colours.fg },
    TSConstBuiltin = { fg = colours.colour4 },
    TSConstMacro = { fg = colours.colour4 },
    TSConstructor = { fg = colours.colour2, bold = true },
    TSException = { fg = colours.colour0 },
    TSField = { fg = colours.colou5 },
    TSFloat = { fg = colours.colour4 },
    TSFunction = { fg = colours.colour2 },
    TSFuncBuiltin = { fg = colours.colour2 },
    TSFuncMacro = { fg = colours.colour2 },
    TSInclude = { fg = colours.colour0 },
    TSKeyword = { fg = colours.colour0 },
    TSKeywordFunction = { fg = colours.colour0 },
    TsKeywordOperator = { fg = colours.colour1 },
    TSKeywordReturn = { fg = colours.colour0 },
    TSLabel = { fg = colours.colour1 },
    TSMethod = { fg = colours.colour2 },
    TSNamespace = { fg = colours.colour6 },
    TSNumber = { fg = colours.colour4 },
    TSParameter = { fg = colours.fg },
    TSParameterReference = { fg = colours.fg },
    TSProperty = { fg = colours.colour3 },
    TSPunctDelimiter = { fg = colours.colour7 },
    TSPunctBracket = { fg = colours.fg },
    TSPunctSpecial = { fg = colours.colour3 },
    TSRepeat = { fg = colours.colour0 },
    TSString = { fg = colours.colour5 },
    TSStringRegex = { fg = colours.colour2 },
    TSStringEscape = { fg = colours.colour2 },
    TSStringSpecial = { fg = colours.colour6 },
    TSSymbol = { fg = colours.fg },
    TSTag = { fg = colours.colour1 },
    TSTagAttribute = { fg = colours.colour2 },
    TSTagDelimiter = { fg = colours.colour2 },
    TSText = { fg = colours.colour2 },
    TSStrong = { fg = colours.none, bg = colours.none, bold = true },
    TSEmphasis = { fg = colours.none, bg = colours.none, italic = true },
    TSUnderline = { fg = colours.none, bg = colours.none, underline = true },
    TSStrike = { fg = colours.none, bg = colours.none, strikethrough = true },
    TSTitle = { fg = colours.colour1 },
    TSLiteral = { fg = colours.colour2 },
    TSURI = { fg = colours.colour3 },
    TSMath = { fg = colours.colour3 },
    TSTextReference = { fg = colours.colour5 },
    TSEnvironment = { fg = colours.colour5 },
    TSEnvironmentName = { fg = colours.colour6 },
    TSNote = { fg = colours.bg, bg = colours.colour2 },
    TSWarning = { fg = colours.bg, bg = colours.colour6 },
    TSDanger = { fg = colours.bg, bg = colours.colour0 },
    TSType = { fg = colours.colour6 },
    TSTypeBuiltin = { fg = colours.colour6 },
    TSVariable = { fg = colours.fg },
    TSVariableBuiltin = { fg = colours.colour4 },
  }
end
