backend = "glx"

animations = (
  {
    triggers = ["open", "show"];
    preset = "appear";
    duration = 0.25;
    scale = 0;
  },
  {
    triggers = ["close", "hide"];
    preset = "disappear";
    duration = 0.25;
    scale = 0;
  },
  {
    triggers = ["geometry"];
    preset = "geometry-change";
  }
)

rules = (
  {
    match = "class_i = 'awesome'";
    animations = (
      { triggers = ["open", "show"]; },
      { triggers = ["close", "hide"]; }
      { triggers = ["geometry"]; }
    );
  }
)
