backend = "glx"

corner-radius = 8

animations = (
  {
    triggers = ["close", "hide"];
    preset = "disappear";
    duration = 0.25;
    scale = 0;
  },
  {
    triggers = ["open", "show"];
    preset = "appear";
    duration = 0.25;
    scale = 0;
  },
  {
    triggers = ["geometry"];
    preset = "geometry-change";
    duration = 0.2;
  }
);

rules = (
  {
    match = "class_i = 'awesome'";
    corner-radius = 0
    animations = (
      { triggers = ["open", "show"]; },
      { triggers = ["close", "hide"]; },
      { triggers = ["geometry"]; }
    );
  }
);
