live_config_reload = true

[window]
opacity = 1
decorations = "none"

[window.padding]
x = 24
y = 24

[cursor]
blink_interval = 500
unfocused_hollow = false

[cursor.style]
blinking = "Off"
shape = "Block"
