env:
  TERM: alacritty

##### Set Window Preferences #####
window:
  opacity: 1
  decorations: none

  dimensions:
    columns: 82
    lines: 23

  padding:
    x: 40
    y: 40

##### Scrolling #####
scrolling:
  history: 10000
  multiplier: 3

live_config_reload: true
