[font]
size = 18

[font.normal]
family = "PlemolJP Console NF"
style = "Regular"

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.offset]
x = 0
y = 0
