[font]
size = 16

[font.normal]
family = "Maple Mono NF"
style = "Light"

[font.bold]
style = "Bold"

[font.bold_italic]
style = "Bold Italic"

[font.italic]
style = "Italic"

[font.offset]
x = 0
y = 0
