palette = "catppuccin_macchiato"

format = """
$directory
$character"""
right_format = "$git_branch"

[character]
success_symbol = "[>](yellow)"
error_symbol = "[>](yellow)"

[directory]
style = "blue"

[git_branch]
symbol = '󰘬 '
truncation_length = 20
truncation_symbol = ''
# ignore_branches = ['main']
format = "[$symbol$branch]($style)"
style = "sky"

[palettes.catppuccin_macchiato]
yellow = "#eed49f"
sky = "#91d7e3"
blue = "#8aadf4"
