format = """
$directory\
$character"""
right_format = "$git_branch"

[character]
format = " "

[directory]
format = "[ [$read_only]($read_only_style)$path ]($style)"
style = "bg:black"
truncation_symbol = "<"
truncation_length = 3
read_only = "󰌾 "
read_only_style = "fg:red bg:black"

[git_branch]
truncation_length = 20
truncation_symbol = ''
format = "[ $branch(:$remote_branch) ]($style)"
style = "bg:black"
